version: "3.5"
services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - PUID=0
      - PGID=0
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=${MYSQL_HOST}
      - GITEA__database__NAME=${GITEA_MYSQL_DATABASE_NAME}
      - GITEA__database__USER=${GITEA_MYSQL_DATABASE_USERNAME}
      - GITEA__database__PASSWD=${GITEA_MYSQL_DATABASE_PASSWORD}
    restart: always
    volumes:
      - "${GITEA_VOLUME}:/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.gitea.rule=Host(`gitea.example.com`)'
      - 'traefik.http.routers.gitea.entrypoints=https'
      - 'traefik.http.routers.gitea.tls=true'
      - 'traefik.http.routers.gitea.tls.options=default'
      - 'traefik.http.services.gitea.loadbalancer.server.port=3000'
    ports:
      - "${GITEA_SSH_PROXY_PORT}:22"
networks:
  default:
      name: example.com
      external: true