version: '3.8'
services:
  bark-server:
    image: finab/bark-server
    container_name: bark-server
    restart: always
    volumes:
      - ./data:/data
    expose:
      - "8080"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.bark-server.rule=Host(`bark.example.com`)'
      - 'traefik.http.routers.bark-server.entrypoints=https'
      - 'traefik.http.routers.bark-server.tls=true'
      - 'traefik.http.routers.bark-server.tls.options=default'
      - "traefik.http.services.bark-server.loadbalancer.server.port=8080"
networks:
  default:
      name: example.com
      external: true